import express from "express";
import PDFDocument from "pdfkit";
import { PrivacyReport, Resume } from "../lib/models.js";
import { scanPrivacyRisks } from "../services/privacy.js";

const router = express.Router();

function sanitizePdfText(value = "") {
  return String(value)
    .replace(/^%PDF-[\s\S]*?obj\s*/i, "")
    .replace(/%[A-Z0-9_.-]{1,8}/gi, "")
    .replace(/[^\S\r\n]+/g, " ")
    .replace(/[\u2022\u25CF\u25E6\u2219\u00B7]/g, "-")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// Scan resume for privacy risks
router.post("/scan", async (req, res) => {
  try {
    const { resumeId, content } = req.body;
    // Use a valid MongoDB ObjectId for testing: 000000000000000000000001
    const userId = req.user?.id || "000000000000000000000001";

    if (!content) {
      return res.status(400).json({ error: "content is required" });
    }

    // If resumeId is provided, verify it belongs to user
    if (resumeId) {
      const resume = await Resume.findOne({ _id: resumeId, userId });
      if (!resume) {
        return res.status(404).json({ error: "Resume not found" });
      }
    }

    // Scan for privacy risks
    const scanResult = await scanPrivacyRisks(content);

    const reportPayload = {
      userId,
      resumeId: resumeId || null,
      risks: scanResult.risks,
      riskScore: scanResult.riskScore,
      privacyScore: scanResult.privacyScore,
      riskLevel: scanResult.riskLevel,
      versions: scanResult.versions,
      insights: scanResult.insights,
      advisorMessages: scanResult.advisorMessages,
      auditLog: scanResult.auditLog,
      redactedContent: scanResult.redactedContent,
    };

    let report = {
      ...reportPayload,
      ...scanResult,
      createdAt: new Date(),
    };
    try {
      if (PrivacyReport.db.readyState !== 1) {
        throw new Error("MongoDB is not connected");
      }
      const savedReport = new PrivacyReport(reportPayload);
      await savedReport.save();
      report = {
        ...savedReport.toObject(),
        ...scanResult,
      };
    } catch (saveError) {
      console.warn("Could not save privacy report, returning unsaved report:", saveError.message);
    }
    res.json({ report, message: "Privacy scan completed" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: error.message });
  }
});

router.post("/export-pdf", async (req, res) => {
  try {
    const { content = "", title = "ResuMatch Redacted Resume" } = req.body || {};
    const cleanContent = sanitizePdfText(content || "No content provided.");

    const doc = new PDFDocument({
      margin: 48,
      size: "A4",
      info: {
        Title: title,
        Author: "ResuMatch Privacy Center",
      },
    });

    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => {
      const pdf = Buffer.concat(chunks);
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="${title.replace(/[^a-z0-9-]+/gi, "-").toLowerCase()}.pdf"`);
      res.send(pdf);
    });

    doc
      .font("Helvetica-Bold")
      .fontSize(18)
      .fillColor("#0f172a")
      .text(title, { align: "left" })
      .moveDown(0.5);
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#64748b")
      .text(`Generated by ResuMatch Privacy Center on ${new Date().toLocaleString()}`)
      .moveDown(1);
    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#111827")
      .text(cleanContent, {
        align: "left",
        lineGap: 3,
        paragraphGap: 4,
      });
    doc.end();
  } catch (error) {
    console.error("Privacy PDF export error:", error);
    res.status(500).json({ error: "Failed to export privacy PDF" });
  }
});

// Get privacy reports for user
router.get("/reports", async (req, res) => {
  try {
    const userId = req.user?.id || "000000000000000000000001";

    const reports = await PrivacyReport.find({ userId })
      .populate("resumeId")
      .sort({ createdAt: -1 });

    res.json({ reports });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: error.message });
  }
});

// Get specific privacy report
router.get("/reports/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id || "000000000000000000000001";

    const report = await PrivacyReport.findOne({ _id: id, userId })
      .populate("resumeId");

    if (!report) {
      return res.status(404).json({ error: "Privacy report not found" });
    }

    res.json({ report });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: error.message });
  }
});

// Get redacted content from report
router.get("/reports/:id/redacted", async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id || "000000000000000000000001";

    const report = await PrivacyReport.findOne({ _id: id, userId });

    if (!report) {
      return res.status(404).json({ error: "Privacy report not found" });
    }

    res.json({ content: report.redactedContent });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: error.message });
  }
});

// Mark privacy report as reviewed
router.put("/reports/:id/review", async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id || "000000000000000000000001";

    const report = await PrivacyReport.findOne({ _id: id, userId });

    if (!report) {
      return res.status(404).json({ error: "Privacy report not found" });
    }

    report.reviewedAt = new Date();
    await report.save();

    res.json({ report, message: "Privacy report marked as reviewed" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: error.message });
  }
});

export default router;
